// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9a2Szrv86quBwS9ZUfKJug4VLUMctPJ8',
    appId: '1:512370141483:web:0d2128470f72c75afbfd6e',
    messagingSenderId: '512370141483',
    projectId: 'test-database-7d8af',
    authDomain: 'test-database-7d8af.firebaseapp.com',
    storageBucket: 'test-database-7d8af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmFVy5VZ5nW0X9cNN-OxyApD9d4ub-Gk',
    appId: '1:512370141483:android:a1679cc1d6274d65fbfd6e',
    messagingSenderId: '512370141483',
    projectId: 'test-database-7d8af',
    storageBucket: 'test-database-7d8af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeNmpfIUZ417Qo4udelgQDY7cgKhQ1vqM',
    appId: '1:512370141483:ios:7d2672b981a189d6fbfd6e',
    messagingSenderId: '512370141483',
    projectId: 'test-database-7d8af',
    storageBucket: 'test-database-7d8af.appspot.com',
    iosBundleId: 'com.example.petersProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeNmpfIUZ417Qo4udelgQDY7cgKhQ1vqM',
    appId: '1:512370141483:ios:7d2672b981a189d6fbfd6e',
    messagingSenderId: '512370141483',
    projectId: 'test-database-7d8af',
    storageBucket: 'test-database-7d8af.appspot.com',
    iosBundleId: 'com.example.petersProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9a2Szrv86quBwS9ZUfKJug4VLUMctPJ8',
    appId: '1:512370141483:web:362df5f06b722678fbfd6e',
    messagingSenderId: '512370141483',
    projectId: 'test-database-7d8af',
    authDomain: 'test-database-7d8af.firebaseapp.com',
    storageBucket: 'test-database-7d8af.appspot.com',
  );

}